# Generated by Django 6.0.4 on 2026-04-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address_uz', models.TextField(verbose_name='Manzil (UZ)')),
                ('address_ru', models.TextField(blank=True, verbose_name='Manzil (RU)')),
                ('address_en', models.TextField(blank=True, verbose_name='Manzil (EN)')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('map_embed_url', models.TextField(blank=True, help_text='Google Maps iframe src URL', verbose_name='Google Maps Embed URL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': "Kompaniya ma'lumotlari",
                'verbose_name_plural': "Kompaniya ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildimi?")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kontakt xabar',
                'verbose_name_plural': 'Kontakt xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1_uz', models.CharField(max_length=200, verbose_name='Sarlavha 1 (UZ)')),
                ('title1_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha 1 (RU)')),
                ('title1_en', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha 1 (EN)')),
                ('title2_uz', models.CharField(max_length=200, verbose_name='Sarlavha 2 (UZ)')),
                ('title2_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha 2 (RU)')),
                ('title2_en', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha 2 (EN)')),
                ('subtitle_uz', models.TextField(blank=True, verbose_name="Qo'shimcha matn (UZ)")),
                ('subtitle_ru', models.TextField(blank=True, verbose_name="Qo'shimcha matn (RU)")),
                ('subtitle_en', models.TextField(blank=True, verbose_name="Qo'shimcha matn (EN)")),
                ('button_text_uz', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni (UZ)')),
                ('button_text_ru', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni (RU)')),
                ('button_text_en', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni (EN)')),
                ('button_url', models.CharField(blank=True, default='#services', max_length=300, verbose_name='Tugma URL')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Fon rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Bannerlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (EN)')),
                ('content_uz', models.TextField(blank=True, verbose_name='Matn (UZ)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (RU)')),
                ('content_en', models.TextField(blank=True, verbose_name='Matn (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('date', models.DateField(help_text='Yangilik sanasi', verbose_name='Sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Nomi (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (EN)')),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Rasm')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/videos/', verbose_name='Video')),
                ('category', models.CharField(choices=[('web', 'Veb-sayt'), ('mobile', 'Mobil ilova'), ('crm', 'CRM/ERP'), ('video', 'Video Production'), ('ai', 'AI & Akademiya'), ('cloud', 'Cloud Computing'), ('other', 'Boshqa')], default='web', max_length=20, verbose_name='Kategoriya')),
                ('url', models.URLField(blank=True, help_text="Tashqi havola (agar bo'lsa)", verbose_name='Loyiha URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('icon', models.CharField(choices=[('laptop', 'Laptop — Veb-sayt'), ('smartphone', 'Smartphone — Mobil ilova'), ('database', 'Database — ERP/CRM'), ('pen-tool', 'PenTool — UI/UX Dizayn'), ('shield-check', 'ShieldCheck — Xavfsizlik'), ('video', 'Video — Video Production'), ('graduation-cap', 'GraduationCap — Akademiya'), ('cloud', 'Cloud — Bulutli texnologiyalar')], default='laptop', help_text='Lucide icon nomi (frontendda ishlatiladi)', max_length=50, verbose_name='Ikona')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Ism (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Ism (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Ism (EN)')),
                ('position_uz', models.CharField(max_length=200, verbose_name='Lavozim (UZ)')),
                ('position_ru', models.CharField(blank=True, max_length=200, verbose_name='Lavozim (RU)')),
                ('position_en', models.CharField(blank=True, max_length=200, verbose_name='Lavozim (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Rasm')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
                'ordering': ['order', 'id'],
            },
        ),
    ]
